### ISSUE TITLE
Smetana compatibility

### ISSUE THREAD

**Issue by arianccbasile** [jotech/gapseq#39]
Hello, 
I have generated some models with your source and I was trying to analyze them with Smetana software (https://github.com/cdanielmachado/smetana). I set the parameter --ext to e0 to change the extracellular compartment identifier in the models. However, I get an error from an inner compound probably always due to compartments nomenclature. Here the command line and the error I get. Do you have any suggestion?

`smetana --global *.xml --flavor fbc2 --verbose --ext e0`

```
Loading community: all
Traceback (most recent call last):
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/bin/smetana", line 468, in <module>
    ignore_coupling=args.no_coupling,
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/bin/smetana", line 333, in main
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/bin/smetana", line 333, in <listcomp>
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/io/cache.py", line 24, in get_model
    model = load_cbmodel(self.paths[model_id], **self.load_args)
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/io/sbml.py", line 146, in load_cbmodel
    load_gprs=load_gprs, load_metadata=load_metadata)
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/io/sbml.py", line 104, in load_sbml_model
    load_gprs=load_gprs, load_metadata=load_metadata)
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/io/sbml.py", line 306, in _load_cbmodel
    _load_metabolites(sbml_model, model, flavor, load_metadata=load_metadata)
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/io/sbml.py", line 180, in _load_metabolites
    model.add_metabolite(_load_metabolite(species, flavor, load_metadata=load_metadata), clear_tmp=False)
  File "/mnt/data_SSD/anaconda3/envs/flux_balance/lib/python3.6/site-packages/framed/model/model.py", line 323, in add_metabolite
    raise KeyError("Failed to add metabolite '{}' (invalid compartment)".format(metabolite.id))
KeyError: "Failed to add metabolite 'M_cpd15561_c0' (invalid compartment)"

```

Sincerely,
Arianna Basile

**Comment by arianccbasile** [comment]
I solved it with Professor Daniel Machado. Here for the solution [Smetana #12](https://github.com/cdanielmachado/smetana/issues/12).

Sincerely,
Arianna Basile

**Comment by Waschina** [comment]
Hi Arianna,
I am currently trying to reproduce the error. Would it be possible for you to share the model's xml-File (if you prefer also via email)? This would help to find the source of this issue.
Thanks,
Silvio (s.waschina[at]nutrinf.uni-kiel.de)

**Comment by arianccbasile** [comment]
I sent an e-mail.
Thank you in advance for your disponibility. 

Sincerely,
Arianna Basile

**Comment by Waschina** [comment]
Dear Arianna,
with the last commit, the NA compartment issue should be resolved. Thanks for filing this issue and your help to improve gapseq.
I hope this enables compatibility with Smetana. If not, please re-open this issue.
Best wishes
Silvio
